apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-app.fullname" . }}
  labels:
    {{- include "cert-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "cert-app.selectorLabels" . | nindent 4 }}
